### ISSUE TITLE
anaconda-project should provide plugins cookiecutter functionality

### ISSUE THREAD

**Issue by fpliger** [Anaconda-Platform/anaconda-project#102]
After #89 lands we also need a way to help users creating plugins... I.e. some cookiecutter command that would prepare the project plugin and drive the user to customize it, package it and try it out...

**Comment by bollwyvl** [comment]
Awesome. In addition to generating a canonical plugin development project (right?), core or plugins could include a number of other cookiecutters:
- whole projects
- a command, either in an existing env_spec or a new one (with [hooks](https://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html) that do project things)

While we _should_ distribute the actual cookiecutters in the end-user package, we may not want `cookiecutter` directly in the dependency chain (it carries a number of dependencies that duplicate things already in this repo... another yaml parser, etc)... but still be available, tested, and documented.

Riffing on the "private environment" idea, one approach to this would be to create a temporary project that has a (pinned) version of cookiecutter:

```
$> anaconda-project template plugin
`cookiecutter` is not installed in the same environment as `anaconda-project`. 

Use a private project? [Y/n]
```

Something like this:
```yaml
name: cookiecutter-anaconda-project-plugin-bootstrap
packages:
- cookiecutter=1.5.1
commands:
  cookiecutter:
    unix: cookiecutter
    windows: cookiecutter
```
