### ISSUE TITLE
pip packages not working

### ISSUE THREAD

**Issue by danielfrg** [Anaconda-Platform/anaconda-project#106]
The `pip` section in `packages` is not working correctly.

Affects: `anaconda-project==0.8.0`

Example project yaml:

```yaml
name: hola

commands:
  default:
    notebook: notebook.ipynb
    env_spec: default

env_specs:
  default:
    description: Default environment spec for running commands
    packages:
    - notebook
    - pandas
    - scikit-learn
    - statsmodels
    - matplotlib
    - seaborn
    - pydotplus
    - py-xgboost
    - graphviz
    - pip:
      - CHAID==4.0.0
      - word2vec
    channels: []
    platforms:
    - linux-64
    - osx-64
    - win-64
```

Doing prepare will pip install both `CHAID` and `word2vec` in the environment where `anaconda-project` is installed and not in the `default` environment.

**Comment by havocp** [comment]
seems likely to be somehow related to pip version

**Comment by danielfrg** [comment]
I am using `pip 9.0.1`. Maybe if I downgrade python to downgrade pip?

**Comment by danielfrg** [comment]
After looking at one project that does work with `pip` and worked for me in the same setup I tried a bunch of stuff the actual error was the directory name that has the `anaconda-project.yml`.

I had a `22-classification-and-regression-trees` directory and if i change it to `22-classification` it works fine.

I don't know  if its the length of the whole path or just the last directory name or if its pip or what  but I just tried this multiple times and I can reproduce (on MacOS).

**Comment by danielfrg** [comment]
I honestly don't know whats happening anymore :) but this combination of settings made it work for me:

```
name: 22-classification-and-regression

commands:
  default:
    notebook: classification-and-regression.ipynb
    env_spec: default

packages:
  - python=3.5
  - notebook
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - pydotplus
  - py-xgboost
  - graphviz
  - pip:
    - treelib
    - CHAID

env_specs:
  default:
    channels: []
    packages: []
```

**Comment by danielfrg** [comment]
Another example that doesn't work

```
name: 28-thrid-party

commands:
  default:
    unix: python main.py

packages:
  - python=3.5
  - notebook
  - pandas
  - pip:
    - dash

env_specs:
  default:
    channels: []
    packages: []
```

Now I actually don't know I thought it was the python version that made the previous one work but i guess not...
