### ISSUE TITLE
anaconda-project switching between prompts for commands on Windows

### ISSUE THREAD

**Issue by ghost** [Anaconda-Platform/anaconda-project#154]
When running a command that displays output, the prompt is returned before the command is fully executed. This happens in Git Bash, Hyper, and cmd.exe on Windows. Although this example is trivial, it leads to larger issues with commands that use interactive prompts

#### anaconda-project.yml

```
name: test

commands:
  pyi:
    windows: python -i 
    env_spec: foo
  pyp:
    windows: python -c "import time;time.sleep(5);print('\nexample\noutput')"
    env_spec: foo
env_specs:
  foo:
    packages:
      - python >=3.6,<3.7
```

Running `anaconda-project pyp`:
```

C:\Users\user\Desktop\test>anaconda-project run pyp

C:\Users\user\Desktop\test>
example
output
```

The expected result should be printing before the prompt gets returned.

Running `anaconda-project pyi` switches between the normal prompt and the python prompt

```
C:\Users\user\Desktop\test>anaconda-project run py

C:\Users\user\Desktop\test>Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import this
'import' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\user\Desktop\test>anaconda-project run pyp
  File "<stdin>", line 1
    anaconda-project run pyp
                       ^
SyntaxError: invalid syntax
>>>
C:\Users\user\Desktop\test>
>>>
C:\Users\user\Desktop\test>
>>>
C:\Users\user\Desktop\test>
>>>
C:\Users\user\Desktop\test>
>>>
```

This was all done by creating the `anaconda-project.yml` file and running `anaconda-project prepare`.
