### ISSUE TITLE
Issues Running anaconda-projects commands in a subdirectory

### ISSUE THREAD

**Issue by AlbertDeFusco** [Anaconda-Platform/anaconda-project#190]
When I run `anaconda-project` commands in a subdirectory of my project I end up with new `anaconda-project.yml` files in those subdirectories.

## 1. Prepare project
Here's my `anaconda-project.yml` file

```yaml
name: subdirectories
  
packages:
    - python=3.7
    - requests
channels: []

env_specs:
  env:
    packages: []
    channels: []
```

then I run `anaconda-project prepare`

## 2. Make subdirectory
```
> mkdir dir1
```

## 3. Attempt to add a package from within subdirectory
```
> cd dir1
> anaconda-project add-packages numba
```

I end up with a new `anaconda-project.yml` in `dir1` with the contents consistent with running the following two commands in `dir1`.

```
> anaconda-project init
> anaconda-project add-packages numba
```
