### ISSUE TITLE
pip and HTTP_PROXY

### ISSUE THREAD

**Issue by zdog234** [Anaconda-Platform/anaconda-project#191]
This might be the same issue as #16, but I'm not quite sure.

I'm trying to run `anaconda-project prepare` in an Anaconda Enterprise environment with an `environment.yml` that I've added below.

<details>
<summary>environment.yml</summary>

```yaml
name: Python 3.6

description: A comprehensive project template that contains all of the packages available
  in the Anaconda Distribution v5.0.1 for Python 3.6. Get started with the most popular
  and powerful packages in data science.
channels: []
packages: []
platforms:
- win-64
- linux-64
- osx-64

env_specs:
  service:
    description: "The Prod environment for the Datarobot Training Service"
    packages:
    - python=3.6
    - scikit-learn
    - pip:
      - flask-restful
      - flask
variables:
  HTTP_PROXY: http://proxyvipecc.nb.ford.com:83
  HTTPS_PROXY: https://proxyvipecc.nb.ford.com:83
  NO_PROXY: ford.com
```

</details>

All of the conda packages install just fine, but I get a warning about the pip packages not being installed. It's hard to copy contents from jupyter terminals, but I'll try to transcribe it here:

```
missing requirement to run this project: The project needs a Conda environment containing all required packages.
  Conda environment is missing packages: flask, flask-restful
(Use Ctrl+C to quit.)
Value for HTTP_PROXY:
```
It seems like the environment variables are set *after* the pip install commands are run. Would it fit into `anaconda-project`'s design to set environment variables before creating environments when running `prepare`?

Thanks!
