### ISSUE TITLE
Add require section to commands

### ISSUE THREAD

**Issue by jsignell** [Anaconda-Platform/anaconda-project#195]
It would be nice to have a require section on commands that allows the user to pass a list of variable names. These would be the variables that are required to run the specific command. 
Something like:

```yaml
commands:
  notebook:
    notebook: bay_trimesh.ipynb
    require: 
      - DATA
  test:
    unix:    pytest --nbsmoke-run -k *.ipynb --ignore envs
  lint:
    unix:    pytest --nbsmoke-lint -k *.ipynb --ignore envs
    require: []

variables: {}
downloads:
  DATA:
    url: https://s3.amazonaws.com/datashader-data/Chesapeake_and_Delaware_Bays.zip
    filename: data
    unzip: true
```

`require` would default to the list of variables + downloads by default. So then if the user ran `anaconda-platform run lint` they would not have the download happen first. But if they run `test` or `notebook` they will.
