### ISSUE TITLE
Support multiline commands

### ISSUE THREAD

**Issue by jsignell** [Anaconda-Platform/anaconda-project#196]
It would be helpful to be able to write a multiline command similar to how you can do in travis. This would look like:

```yaml
  lint:
    unix:    
      - flake8
      - pytest --nbsmoke-lint -k *.ipynb --ignore envs
    env_spec: test
```

**Comment by jbednar** [comment]
Yes, that would be useful.  

What should happen when "supports_http_options: true"?  It's unlikely that in any given series of commands, *all* of the commands would support the HTTP options like `--anaconda-project-port`. Assuming that some commands might be preparing for an eventual deployment, maybe the http options would be given only to the _last_ command in this list?

**Comment by jsignell** [comment]
That seems reasonable.

**Comment by AlbertDeFusco** [comment]
This should already work Could you give it a try?

```yaml
lint:
  unix: |
    flake8
    pytest --nbsmoke-lint -k *.ipynb --ignore envs
  env_spec: test
```

I've used to successfully launch a webserver and run a script.


```
commands:
  web:
    unix: |
      python -m http.server 8086 &
      python autompg.py
```
