### ISSUE TITLE
execute custom scripts on prepare

### ISSUE THREAD

**Issue by mcg1969** [Anaconda-Platform/anaconda-project#239]
It would be good if there is a way to execute a script of some sort upon environment preparation.

**Comment by AlbertDeFusco** [comment]
Would something like this fulfill this need? Multiple commands could be tagged as `run_after_prepare` and they would execute in the order shown in the YAML file when running `anaconda-project prepare`.

Or do you think a more specialized specification of post-prepare commands be more inline with what you want?

```yaml
name: prepare-with-script

packages:
  - python=3.8

env_specs:
  default: {}

commands:
  my-command:
    unix: <some action here>
    win: <some action here>
    env_spec: default
    run_after_prepare: True
```
