### ISSUE TITLE
anaconda-project lock fails for env_specs with no packages

### ISSUE THREAD

**Issue by sanbales** [Anaconda-Platform/anaconda-project#260]
When composing environments, sometimes it is useful to create an `env_spec` that specifies things that can be inherited by other environments, but have no packages in themselves.

When you try to lock such a project file, you get a TypeError 

`TypeError: ('must specify a list of one or more packages to install into existing environment, not %r', ())`

Would it be possible to skip such environments and may just put out a warning?

I've shared an illustrative example of such an `anaconda-project.yml` below.  `anaconda-project lock` fails when it gets to the `_channels` env_spec.

```
name: main_environment

platforms:
  - linux-64
  - win-64

env_specs:
  my_main_env:
    description: the actual end-user environment
    inherit_from:
      - _lab
    packages:
      - numpy
      - scipy
      - spacy

  _jsbuild:
    description: the build env for a JupyterLab app_dir
    inherit_from:
      - _lab
      - _js

  ### The environments below contain the common dependencies
  ### these environments are never installed
  _channels:
    description: all our channels (never installed)
    channels:
      - conda-forge
      - defaults

  _py:
    description: our python version (never installed)
    inherit_from:
      - _channels
    packages:
      - python >=3.7,<3.8.0a0

  _js:
    description: our node (never installed)
    inherit_from:
      - _channels
    packages:
      - nodejs >=12.16.0,<13.0.0a0

  _conda:
    description: our conda version (never installed)
    inherit_from:
      - _py
    packages:
      - conda >=4.8,<4.9.0a0
      - python-libarchive-c

  _lab:
    description: capture our JupyterLab dependencies (never installed)
    inherit_from:
      - _py
    packages:
      - jupyterlab >=1.0,<2

```
