### ISSUE TITLE
Regression in support for multiple env_specs in anaconda-project lock

### ISSUE THREAD

**Issue by jlstevens** [Anaconda-Platform/anaconda-project#320]
While working on https://github.com/pyviz-topics/examples/pull/145 I found that the output of `anaconda-project lock` has changed since version 0.8.2 given the same `anaconda-project.yml`. 

If you use 0.8.2 the `test` environment in the [`env_spec`](https://github.com/pyviz-topics/examples/blob/master/boids/anaconda-project.yml#L42) is locked and re-created properly. But in 0.9.0 and 0.9.1 the `pytest` package no longer appears anywhere in the lock file.

**Comment by AlbertDeFusco** [comment]
It looks like there is some room for improvement here, but I would say it's not recommended to use both `packages` and `dependencies`. I would that you must match the package spec key between global and env-spec. Note that `dependencies` is preferred as of version 0.9.1 and will ignore `packages` if both are found.

I have enumerated three working scenarios.

## Dependencies-only

```yaml
name: lock-deps

dependencies:
- python=3.7.6

platforms:
- linux-64
- osx-64
- win-64

env_specs:
  default: {}
  test:
    dependencies:
      - pytest
```

```
> anaconda-project lock
> grep pytest anaconda-project-lock.yml
      - pytest=6.2.3=py37h06a4308_2
      - pytest=6.2.3=py37hecd8cb5_2
      - pytest=6.2.3=py37haa95532_2
```

## Packages-only

```yaml
name: lock-deps

packages:
- python=3.7.6

platforms:
- linux-64
- osx-64
- win-64

env_specs:
  default: {}
  test:
    packages:
      - pytest
```

```
> anaconda-project lock
> grep pytest anaconda-project-lock.yml
      - pytest=6.2.3=py37h06a4308_2
      - pytest=6.2.3=py37hecd8cb5_2
      - pytest=6.2.3=py37haa95532_2
```

## Mixed

Here is a backwards compatible `anaconda-project.yml` file that can also serve as a valid `environment.yml` file. If `dependencies` is left off of the `env_spec: test` key you will get the failure specified.

```yaml
name: lock-deps

packages: &pkgs
- python=3.7.6

dependencies: *pkgs
 
platforms:
- linux-64
- osx-64
- win-64

env_specs:
  default: {}
  test:
    packages: &testpkgs
      - pytest
    dependencies: *testpkgs
```

```
> anaconda-project lock
> grep pytest anaconda-project-lock.yml
      - pytest=6.2.3=py37h06a4308_2
      - pytest=6.2.3=py37hecd8cb5_2
      - pytest=6.2.3=py37haa95532_2
```
