### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mmejia10** [Anaconda-Platform/anaconda-project#377]
If your issue really is with anaconda project, please delete the above text and fill this out!

#### ALL software version info
(anaconda-project version, conda version, etc.)

anaconda-project --version
0.9.1

#### Description of expected behavior and the observed behavior

The customer is trying to install a package via Pip and it fails, customer would like more logs for the reason it fails. I have used the --verbose flag however it excludes the details for pip install.

Running Anaconda-project --verbose prepare gives the following. Its uses the --quiet flag, customer would like this flag to be reomved. 
 $ /opt/continuum/anaconda/envs/env_test_package100/bin/pip install --quiet optbinning

#### Relevant configuration files

```
# E.g. your anaconda-project.yml file

name: Exemple snowflake connection for python

description: This projects show how to use snowflake with python

env_specs:
  env_test_package100:
    packages:
      - pip: 
        - optbinning
        
commands:
    test_snowflake_base:
        unix: python main.py
        env_spec: env_test_package100

  

# Complete, minimal, self-contained example code that reproduces the issue

```
# list of commands you executed

```

#### Command output and/or screenshots of the bug in action
