### ISSUE TITLE
[BUG] environments aren't created unless referenced in commands

### ISSUE THREAD

**Issue by bkreider** [Anaconda-Platform/anaconda-project#381]
If you remove the commands below, only one environment is created.  It requires both commands to have both envs created. 

```
name: env_wnorm

commands:
  dostuff:
    env_spec: env_rwnorm
    windows: ' '
  default:
    windows: ' '

env_specs:

  default:
    description: env_wnorm
    packages:
    - python=3.8

  env_rwnorm:
    description: env_rwnorm
    packages:
    - python=3.7
```
