### ISSUE TITLE
Import env from yaml file

### ISSUE THREAD

**Issue by AlbertDeFusco** [Anaconda-Platform/anaconda-project#49]
I'd like to convert an environment.yml file into a blank anaconda project. Is there a command like `anaconda-project add-env-file` to import the conda environment specification? Here's an example environment.

```yaml
name: my_env
channels:
  - conda-forge
dependencies:
  - python=3
  - jupyter
  - nbformat
  - pandoc
  - bokeh
  - pygithub
  - pip:
    - pypandoc
```

**Comment by goanpeca** [comment]
@AlbertDeFusco I think that if you have an `environment.yml` file inside a directory/folder and then do `anaconda-project init` (or the right command, cant remember now) should search for that and use it.

Is not this the case @havocp ?

**Comment by havocp** [comment]
Yes, if you put environment.yml in a folder and `anaconda-project init` that folder it should import it. You can also cut-and-paste into an anaconda-project.yml that you have (rename `dependencies` to `packages` I think is the only format difference).

**Comment by havocp** [comment]
Are things working for you, can this issue be closed?

**Comment by AlbertDeFusco** [comment]
Perhaps not, I created a new project in Navigator

```yaml
# This is an Anaconda project file.
#
# Here you can describe your project and how to run it.
# Use `anaconda-project run` to run the project.
# The file is in YAML format, please see http://www.yaml.org/start.html for more.
#

#
# Set the 'name' key to name your project
#
name: new_proj
#
# Set the 'icon' key to give your project an icon
#
icon:
#
# In the commands section, list your runnable scripts, notebooks, and other code.
# Use `anaconda-project add-command` to add commands.
#
commands: {}
#
# In the variables section, list any environment variables your code depends on.
# Use `anaconda-project add-variable` to add variables.
#
variables: {}
#
# In the services section, list any services that should be
# available before your code runs.
# Use `anaconda-project add-service` to add services.
#
services: {}
#
# In the downloads section, list any URLs to download to local files
# before your code runs.
# Use `anaconda-project add-download` to add downloads.
#
downloads: {}
#
# In the packages section, list any packages that must be installed
# before your code runs.
# Use `anaconda-project add-packages` to add packages.
#
packages: []
#
# In the channels section, list any Conda channel URLs to be searched
# for packages.
#
# For example,
#
# channels:
#    - https://conda.anaconda.org/asmeurer
#
channels: []
#
# You can define multiple, named environment specs.
# Each inherits any global packages or channels,
# but can have its own unique ones also.
# Use `anaconda-project add-env-spec` to add environment specs.
#
env_specs: {default: {packages: [anaconda], channels: []}}
```

I then copy the `environment.yml` to the project directory.

```
>anaconda-project init
Environment spec 'my_env' from environment.yml is not in anaconda-project.yml.
Unable to load the project.
```

Is there something I have to do to register the environment name?
