### ISSUE TITLE
Change services to be commands

### ISSUE THREAD

**Issue by havocp** [Anaconda-Platform/anaconda-project#87]
"Services" were envisioned as plugins (though the first proof-of-concept example was "redis" as a placeholder). 

A more elegant solution is to make services be commands. So to have a command that depends on Redis, you'd do something along these lines:
```
commands:
   mynotebook.ipynb:
       notebook: mynotebook.ipynb
       variables:
         - REDIS_URL
   redis:
       unix: redis-server -p 1234 # or something, whatever it is
       env_spec: redis
       provides:
          REDIS_URL: redis://localhost:1234

env_specs:
   default:
     - notebook
   redis:
     - redis
```

This allows projects to invent arbitrary commands. Notice that they are "wired up" via environment variables; the notebook command requires `REDIS_URL` (a feature that already exists), while the redis command provides a url variable.

For services which are HTTP servers, we could support something like this:
```
commands:
   image_classifier:
      unix: python classifier.py
      supports_http_options: true
      provides:
        IMAGE_CLASSIFIER_URL: {
            path: /api/v1/classify
        }
```

The idea here is that anaconda-project would construct the URL by choosing an arbitrary available port and other items via `--anaconda-project-*` http options (possible because of `supports_http_options: true`), and we therefore avoid hardcoding some sort of localhost url as in the redis example.

## Implementation approach: swap out the current Redis implementation

Currently there are a lot of tests of the `redis.py` plugin, covering operations such as starting, stopping, listing running services. An implementation approach that tried to keep the intent of all these tests working, while changing from a plugin to a command, would ensure that all currently-solved problems remain solved. For example, storing a pid and a shutdown command would still have to happen. Chances are that a real Redis command needs a wrapper script around `redis-server` to manage some of this, but I'm not sure; we might need a set of conventions (similar to those around `supports_http_options: true`) around service commands.

## Implementation idea: command templates

Right now you can type `anaconda-project add-service redis` and automatically get a Redis service added to your project.

A way to keep this ability would be to have a file like `share/anaconda-project/services/redis` which would contain a yaml snipped to be merged into anaconda-project.yml and perhaps some supporting files (like a wrapper script) to be copied into the project.
